### ISSUE TITLE
Lỗi URL phần tags

### ISSUE THREAD

**Issue by kienvht** [xfrocks/VietnameseFriendlyLink#1]
Chào xfrocks.
Mình có dùng bản VietnameseFriendlyLink 2.0.2
URL threads đều ok.
Nhưng URL của tag mình vẫn bị lỗi. Xin cho hỏi mình có thể fix ở đâu ạ
ví dụ URL của mình đây: https://vnkienthuc.com/tags/ha-ni/

**Comment by daohoangson** [comment]
Oh, cái này chắc là sửa được. Để mình thử xem.

**Comment by daohoangson** [comment]
Cái tag này có phải được tạo trước khi cài add-on không bạn nhỉ?

**Comment by kienvht** [comment]
> Cái tag này có phải được tạo trước khi cài add-on không bạn nhỉ?

cái tag này được tạo khi mình tạo Thread và điền vào mục tags.
Sau đó nó tự tìm từ từ đó trong bài viết ( có dấu và không dấu ) và nó cho link tags này vào ạ

**Comment by kienvht** [comment]
> Cái tag này có phải được tạo trước khi cài add-on không bạn nhỉ?

em check thử thì nếu ko cài addon thì URL thread bị lỗi tiếng việt, URL của tag thì bình thường.
Sau khi cài addon thì URL ko bị lỗi tiếng việt, còn URL tag thì lỗi ạ

**Comment by daohoangson** [comment]
> em check thử thì nếu ko cài addon thì URL thread bị lỗi tiếng việt, URL của tag thì bình thường.

Lúc tắt add-on đi thì URL của tag là gì vậy bạn? Vì cái tag URL này nó được set cố định khi tạo tag nên đáng ra bật tắt add-on thì nó vẫn giữ nguyên là `ha-ni`.

Nếu bây giờ bạn bật add-on và tạo thread mới với tag có tiếng Việt, ví dụ `hà nội 20191223` thì nó sẽ tạo tag với URL bỏ dấu `ha-noi-20191223` (không bị mất chữ `o`).

**Comment by kienvht** [comment]
> > em check thử thì nếu ko cài addon thì URL thread bị lỗi tiếng việt, URL của tag thì bình thường.
> 
> Lúc tắt add-on đi thì URL của tag là gì vậy bạn? Vì cái tag URL này nó được set cố định khi tạo tag nên đáng ra bật tắt add-on thì nó vẫn giữ nguyên là `ha-ni`.
> 
> Nếu bây giờ bạn bật add-on và tạo thread mới với tag có tiếng Việt, ví dụ `hà nội 20191223` thì nó sẽ tạo tag với URL bỏ dấu `ha-noi-20191223` (không bị mất chữ `o`).

à vậy ý a là cái tag này do là em bị sai từ hồi đầu tiên của forums nên nó sai hả anh

**Comment by kienvht** [comment]
> > em check thử thì nếu ko cài addon thì URL thread bị lỗi tiếng việt, URL của tag thì bình thường.
> 
> Lúc tắt add-on đi thì URL của tag là gì vậy bạn? Vì cái tag URL này nó được set cố định khi tạo tag nên đáng ra bật tắt add-on thì nó vẫn giữ nguyên là `ha-ni`.
> 
> Nếu bây giờ bạn bật add-on và tạo thread mới với tag có tiếng Việt, ví dụ `hà nội 20191223` thì nó sẽ tạo tag với URL bỏ dấu `ha-noi-20191223` (không bị mất chữ `o`).

em vừa thử. đúng như anh nói ạ. vậy là do cái tag của em chứ ko phải là do lỗi của addon

**Comment by daohoangson** [comment]
Uh, nếu tag tạo trước khi add-on được cài thì cái tag URL nó generate chưa chuẩn. 

Sau khi cài add-on thì cái URL sẽ generate chuẩn hơn. 

À bạn nhớ update lên v2.0.3 mới nhất nha, có một số điều chỉnh cho nó ngon hơn đó.

Mình close issue này ở đây.
